# Generated by Django 5.1.6 on 2025-02-24 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boneServer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_email", models.EmailField(max_length=254)),
                ("folder_path", models.CharField(max_length=255)),
                (
                    "output_folder_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lower_threshold", models.IntegerField()),
                ("upper_threshold", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
