# Generated by Django 5.1.6 on 2025-04-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boneServer", "0002_segmentationrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentationrecord",
            name="three_d_model_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
